version: '3.8'

services:
  ai-research-feed:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Optional: Mount for development
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "uv", "run", "python", "-c", "import requests; requests.get('http://localhost:5001/debug', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - ai-research-feed
  #   restart: unless-stopped